version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: crown79
      MYSQL_DATABASE: mocksocialmediadb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: bright79
    ports:
      - "3306:3306"
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=host.docker.internal
    links:
      - db
    depends_on:
      - db
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    links:
      - "backend:local"
    depends_on:
      - backend
volumes:
  db:
    driver: local