version: '3'

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=host.docker.internal
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - "80:80"
    links:
      - "backend:local"