export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_TEMPLATE_ID = "SET_TEMPLATE_ID";
export const GET_PREV_TEMPLATES = "GET_PREV_TEMPLATES";
export const PREV_TEMPLATES_SUCCESS = "PREV_TEMPLATES_SUCCESS";
export const PREV_TEMPLATES_FAIL = "PREV_TEMPLATES_FAIL";

export const FETCH_LANGUAGES = "FETCH_LANGUAGES";
export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";
export const FETCH_LANGUAGES_FAIL = "FETCH_LANGUAGES_FAIL";

export const SET_LANGUAGES = "SET_LANGUAGES";
export const SET_LANGUAGES_SUCCESS = "SET_LANGUAGES_SUCCESS";
export const SET_LANGUAGES_FAIL = "SET_LANGUAGES_FAIL";

export const SNACKBAR_SUCCESS = "SNACKBAR_SUCCESS";
export const SNACKBAR_ERROR = "SNACKBAR_ERROR";
export const SNACKBAR_CLEAR = "SNACKBAR_CLEAR";
export const SNACKBAR_INFO = "SNACKBAR_INFO";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const SET_FLOW_STATE = "SET_FLOW_STATE";
export const CLEAR_FLOW_STATE = "CLEAR_FLOW_STATE";
export const MODIFY_ACTIVE_FLOW_STATE = "MODIFY_ACTIVE_FLOW_STATE";
